"""refactor_chat_to_messages

Revision ID: a9cc213a5102
Revises: 7b1827ed4d3e
Create Date: 2025-12-28 08:39:07.855306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9cc213a5102'
down_revision: Union[str, None] = '7b1827ed4d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name='valid_role'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('idx_chat_messages_created', 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_index('idx_chat_messages_session_id', 'chat_messages', ['session_id'], unique=False)
    op.add_column('api_logs', sa.Column('message_id', sa.UUID(), nullable=True))
    op.drop_constraint('api_logs_qa_id_fkey', 'api_logs', type_='foreignkey')
    op.create_foreign_key(None, 'api_logs', 'chat_messages', ['message_id'], ['message_id'], ondelete='SET NULL')
    op.drop_column('api_logs', 'qa_id')
    op.add_column('reasoning_steps', sa.Column('message_id', sa.UUID(), nullable=False))
    op.drop_index('idx_reasoning_steps_qa_id', table_name='reasoning_steps')
    op.drop_index('idx_reasoning_steps_order', table_name='reasoning_steps')
    op.create_index('idx_reasoning_steps_order', 'reasoning_steps', ['message_id', 'step_order'], unique=False)
    op.create_index('idx_reasoning_steps_message_id', 'reasoning_steps', ['message_id'], unique=False)
    op.drop_constraint('reasoning_steps_qa_id_fkey', 'reasoning_steps', type_='foreignkey')
    op.create_foreign_key(None, 'reasoning_steps', 'chat_messages', ['message_id'], ['message_id'], ondelete='CASCADE')
    op.drop_column('reasoning_steps', 'qa_id')
    op.drop_index('idx_qa_pairs_session_created', table_name='qa_pairs')
    op.drop_index('idx_qa_pairs_session_id', table_name='qa_pairs')
    op.execute("DROP TABLE qa_pairs CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reasoning_steps', sa.Column('qa_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reasoning_steps', type_='foreignkey')
    op.create_foreign_key('reasoning_steps_qa_id_fkey', 'reasoning_steps', 'qa_pairs', ['qa_id'], ['qa_id'], ondelete='CASCADE')
    op.drop_index('idx_reasoning_steps_message_id', table_name='reasoning_steps')
    op.drop_index('idx_reasoning_steps_order', table_name='reasoning_steps')
    op.create_index('idx_reasoning_steps_order', 'reasoning_steps', ['qa_id', 'step_order'], unique=False)
    op.create_index('idx_reasoning_steps_qa_id', 'reasoning_steps', ['qa_id'], unique=False)
    op.drop_column('reasoning_steps', 'message_id')
    op.add_column('api_logs', sa.Column('qa_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'api_logs', type_='foreignkey')
    op.create_foreign_key('api_logs_qa_id_fkey', 'api_logs', 'qa_pairs', ['qa_id'], ['qa_id'], ondelete='SET NULL')
    op.drop_column('api_logs', 'message_id')
    op.create_table('qa_pairs',
    sa.Column('qa_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False, comment="User's question"),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False, comment='Final answer with [CITE:...] markers'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], name='qa_pairs_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('qa_id', name='qa_pairs_pkey')
    )
    op.create_index('idx_qa_pairs_session_id', 'qa_pairs', ['session_id'], unique=False)
    op.create_index('idx_qa_pairs_session_created', 'qa_pairs', ['session_id', 'created_at'], unique=False)
    op.drop_index('idx_chat_messages_session_id', table_name='chat_messages')
    op.drop_index('idx_chat_messages_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
