"""Create initial schema

Revision ID: 7b1827ed4d3e
Revises: 
Create Date: 2025-12-26 17:57:57.945512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '7b1827ed4d3e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable pgvector extension BEFORE creating tables
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_raw_data',
    sa.Column('case_id', sa.Integer(), nullable=False, comment='Links to cases.case_id'),
    sa.Column('combined_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Combined API responses'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index('idx_case_raw_data_documents', 'case_raw_data', ['combined_json'], unique=False, postgresql_using='gin', postgresql_ops={'combined_json': 'jsonb_path_ops'})
    op.create_table('cases',
    sa.Column('case_id', sa.Integer(), nullable=False, comment='Clearinghouse case ID'),
    sa.Column('case_name', sa.String(length=500), nullable=False, comment='Case name for display'),
    sa.Column('court', sa.String(length=255), nullable=True, comment='Court name'),
    sa.Column('state', sa.String(length=100), nullable=True, comment='State'),
    sa.Column('filing_date', sa.Date(), nullable=True, comment='Case filing date'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Preprocessing status: queued, processing, ready, failed'),
    sa.Column('preprocessed_at', sa.DateTime(timezone=True), nullable=True, comment='When preprocessing completed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'processing', 'ready', 'failed')", name='valid_status'),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index('idx_cases_status', 'cases', ['status'], unique=False)
    op.create_table('initial_contexts',
    sa.Column('case_id', sa.Integer(), nullable=False, comment='Links to cases.case_id'),
    sa.Column('context_text', sa.Text(), nullable=False, comment='Full initial context'),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('chat_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='References auth.users.id (Supabase Auth)'),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('session_title', sa.String(length=255), nullable=False, comment='Display in sidebar'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('idx_chat_sessions_case_id', 'chat_sessions', ['case_id'], unique=False)
    op.create_index('idx_chat_sessions_updated', 'chat_sessions', ['user_id', 'updated_at'], unique=False)
    op.create_index('idx_chat_sessions_user_id', 'chat_sessions', ['user_id'], unique=False)
    op.create_table('docket_entries',
    sa.Column('docket_entry_id', sa.String(length=50), nullable=False, comment='Citation ID'),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('entry_number', sa.String(length=20), nullable=True, comment='Docket entry number'),
    sa.Column('date_filed', sa.Date(), nullable=True, comment='Filing date'),
    sa.Column('description', sa.Text(), nullable=False, comment='Full docket entry text'),
    sa.Column('url', sa.String(length=1000), nullable=True, comment='CourtListener URL'),
    sa.Column('recap_pdf_url', sa.String(length=1000), nullable=True, comment='RECAP PDF URL'),
    sa.Column('pacer_doc_id', sa.String(length=50), nullable=True, comment='PACER document ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('docket_entry_id')
    )
    op.create_index('idx_docket_entries_case_id', 'docket_entries', ['case_id'], unique=False)
    op.create_index('idx_docket_entries_date', 'docket_entries', ['case_id', 'date_filed'], unique=False)
    op.create_table('documents',
    sa.Column('doc_id', sa.Integer(), nullable=False, comment='Clearinghouse document ID'),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Document title'),
    sa.Column('doc_date', sa.Date(), nullable=True, comment='Document date'),
    sa.Column('document_type', sa.String(length=100), nullable=True, comment='Document type (e.g., Court Order)'),
    sa.Column('file_url', sa.String(length=1000), nullable=True, comment='PDF download URL'),
    sa.Column('clearinghouse_link', sa.String(length=1000), nullable=True, comment='Clearinghouse view URL'),
    sa.Column('total_chunks', sa.Integer(), nullable=False, comment="Total chunks for 'X of Y' display"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index('idx_documents_case_id', 'documents', ['case_id'], unique=False)
    op.create_table('chunks',
    sa.Column('chunk_id', sa.String(length=50), nullable=False, comment='Citation ID'),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='Position in document (0-indexed)'),
    sa.Column('chunk_text', sa.Text(), nullable=False, comment='Full chunk text'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.doc_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id'),
    sa.UniqueConstraint('doc_id', 'chunk_index', name='unique_doc_chunk')
    )
    op.create_index('idx_chunks_case_id', 'chunks', ['case_id'], unique=False)
    op.create_index('idx_chunks_doc_id', 'chunks', ['doc_id'], unique=False)
    op.create_table('qa_pairs',
    sa.Column('qa_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False, comment="User's question"),
    sa.Column('answer', sa.Text(), nullable=False, comment='Final answer with [CITE:...] markers'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('qa_id')
    )
    op.create_index('idx_qa_pairs_session_created', 'qa_pairs', ['session_id', 'created_at'], unique=False)
    op.create_index('idx_qa_pairs_session_id', 'qa_pairs', ['session_id'], unique=False)
    op.create_table('api_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('log_type', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('qa_id', sa.UUID(), nullable=True),
    sa.Column('request_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full request payload'),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full response payload'),
    sa.Column('error_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Error details if failed'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='Request duration in milliseconds'),
    sa.CheckConstraint("log_type IN ('api_request', 'llm_planner_call', 'llm_executor_call', 'llm_embedding_call', 'tool_execution', 'error')", name='valid_log_type'),
    sa.ForeignKeyConstraint(['qa_id'], ['qa_pairs.qa_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('idx_api_logs_errors', 'api_logs', ['timestamp'], unique=False, postgresql_where="log_type = 'error'")
    op.create_index('idx_api_logs_session', 'api_logs', ['session_id'], unique=False)
    op.create_index('idx_api_logs_timestamp', 'api_logs', ['timestamp'], unique=False)
    op.create_index('idx_api_logs_type', 'api_logs', ['log_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_api_logs_timestamp'), 'api_logs', ['timestamp'], unique=False)
    op.create_table('chunk_embeddings',
    sa.Column('chunk_id', sa.String(length=50), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=False, comment='OpenAI embedding vector'),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index('idx_chunk_embeddings_hnsw', 'chunk_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('reasoning_steps',
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('qa_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False, comment='Order within Q&A'),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('step_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Step-specific data'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("step_type IN ('gathered_context', 'reasoning_step', 'tool_call', 'tool_result')", name='valid_step_type'),
    sa.ForeignKeyConstraint(['qa_id'], ['qa_pairs.qa_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id')
    )
    op.create_index('idx_reasoning_steps_order', 'reasoning_steps', ['qa_id', 'step_order'], unique=False)
    op.create_index('idx_reasoning_steps_qa_id', 'reasoning_steps', ['qa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reasoning_steps_qa_id', table_name='reasoning_steps')
    op.drop_index('idx_reasoning_steps_order', table_name='reasoning_steps')
    op.drop_table('reasoning_steps')
    op.drop_index('idx_chunk_embeddings_hnsw', table_name='chunk_embeddings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('chunk_embeddings')
    op.drop_index(op.f('ix_api_logs_timestamp'), table_name='api_logs')
    op.drop_index('idx_api_logs_type', table_name='api_logs')
    op.drop_index('idx_api_logs_timestamp', table_name='api_logs')
    op.drop_index('idx_api_logs_session', table_name='api_logs')
    op.drop_index('idx_api_logs_errors', table_name='api_logs', postgresql_where="log_type = 'error'")
    op.drop_table('api_logs')
    op.drop_index('idx_qa_pairs_session_id', table_name='qa_pairs')
    op.drop_index('idx_qa_pairs_session_created', table_name='qa_pairs')
    op.drop_table('qa_pairs')
    op.drop_index('idx_chunks_doc_id', table_name='chunks')
    op.drop_index('idx_chunks_case_id', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('idx_documents_case_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('idx_docket_entries_date', table_name='docket_entries')
    op.drop_index('idx_docket_entries_case_id', table_name='docket_entries')
    op.drop_table('docket_entries')
    op.drop_index('idx_chat_sessions_user_id', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_updated', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_case_id', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_table('initial_contexts')
    op.drop_index('idx_cases_status', table_name='cases')
    op.drop_table('cases')
    op.drop_index('idx_case_raw_data_documents', table_name='case_raw_data', postgresql_using='gin', postgresql_ops={'combined_json': 'jsonb_path_ops'})
    op.drop_table('case_raw_data')

    # Drop pgvector extension AFTER dropping all tables
    op.execute('DROP EXTENSION IF EXISTS vector')
    # ### end Alembic commands ###
