"""add_llm_logs_table

Revision ID: fcd5911b577f
Revises: 8f63405f9a13
Create Date: 2026-01-11 17:33:48.582112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcd5911b577f'
down_revision: Union[str, None] = '8f63405f9a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('parent_message_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True, comment='The user question being processed'),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False, comment="E.g. 'Planner - Step 1', 'Executor - Tool: search'"),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_llm_logs_created_at', 'llm_logs', ['created_at'], unique=False)
    op.create_index('idx_llm_logs_message_id', 'llm_logs', ['parent_message_id'], unique=False)
    op.create_index('idx_llm_logs_session_id', 'llm_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_llm_logs_id'), 'llm_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_logs_id'), table_name='llm_logs')
    op.drop_index('idx_llm_logs_session_id', table_name='llm_logs')
    op.drop_index('idx_llm_logs_message_id', table_name='llm_logs')
    op.drop_index('idx_llm_logs_created_at', table_name='llm_logs')
    op.drop_table('llm_logs')
    # ### end Alembic commands ###
