"""Create http_request_logs table and drop api_logs table

Revision ID: 8f63405f9a13
Revises: ba082b84c596
Create Date: 2026-01-07 23:02:08.171131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f63405f9a13'
down_revision: Union[str, None] = 'ba082b84c596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('http_request_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False, comment='GET, POST, PUT, DELETE, PATCH, OPTIONS'),
    sa.Column('path', sa.Text(), nullable=False, comment='URL path: /api/chat/sessions'),
    sa.Column('full_url', sa.Text(), nullable=False, comment='Complete URL with query params'),
    sa.Column('client_ip', sa.String(length=50), nullable=True, comment='Client IP address'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='Browser/client user agent string'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='Supabase user ID if authenticated'),
    sa.Column('user_email', sa.String(length=255), nullable=True, comment='User email if authenticated'),
    sa.Column('query_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='URL query parameters as JSON'),
    sa.Column('path_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Path parameters (e.g., {session_id: '...'})"),
    sa.Column('request_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='HTTP request headers'),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full request body for POST/PUT/PATCH'),
    sa.Column('status_code', sa.Integer(), nullable=False, comment='HTTP status code: 200, 404, 500, etc.'),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full response body (if JSON)'),
    sa.Column('response_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='HTTP response headers'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='Request processing time in milliseconds'),
    sa.Column('error_type', sa.String(length=255), nullable=True, comment='Exception class name if error occurred'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if request failed'),
    sa.Column('error_traceback', sa.Text(), nullable=True, comment='Full stack trace for debugging'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('idx_http_logs_errors', 'http_request_logs', ['timestamp'], unique=False, postgresql_where='status_code >= 400')
    op.create_index('idx_http_logs_method_path', 'http_request_logs', ['method', 'path'], unique=False)
    op.create_index('idx_http_logs_path', 'http_request_logs', ['path'], unique=False)
    op.create_index('idx_http_logs_status', 'http_request_logs', ['status_code'], unique=False)
    op.create_index('idx_http_logs_timestamp', 'http_request_logs', ['timestamp'], unique=False)
    op.create_index('idx_http_logs_user', 'http_request_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_http_request_logs_timestamp'), 'http_request_logs', ['timestamp'], unique=False)
    op.drop_index('idx_api_logs_errors', table_name='api_logs', postgresql_where="((log_type)::text = 'error'::text)")
    op.drop_index('idx_api_logs_session', table_name='api_logs')
    op.drop_index('idx_api_logs_timestamp', table_name='api_logs')
    op.drop_index('idx_api_logs_type', table_name='api_logs')
    op.drop_index('ix_api_logs_timestamp', table_name='api_logs')
    op.drop_table('api_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_logs',
    sa.Column('log_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('log_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('request_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Full request payload'),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Full response payload'),
    sa.Column('error_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Error details if failed'),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True, comment='Request duration in milliseconds'),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.CheckConstraint("log_type::text = ANY (ARRAY['api_request'::character varying, 'llm_planner_call'::character varying, 'llm_executor_call'::character varying, 'llm_embedding_call'::character varying, 'tool_execution'::character varying, 'error'::character varying]::text[])", name='valid_log_type'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.message_id'], name='api_logs_message_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], name='api_logs_session_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id', name='api_logs_pkey')
    )
    op.create_index('ix_api_logs_timestamp', 'api_logs', ['timestamp'], unique=False)
    op.create_index('idx_api_logs_type', 'api_logs', ['log_type', 'timestamp'], unique=False)
    op.create_index('idx_api_logs_timestamp', 'api_logs', ['timestamp'], unique=False)
    op.create_index('idx_api_logs_session', 'api_logs', ['session_id'], unique=False)
    op.create_index('idx_api_logs_errors', 'api_logs', ['timestamp'], unique=False, postgresql_where="((log_type)::text = 'error'::text)")
    op.drop_index(op.f('ix_http_request_logs_timestamp'), table_name='http_request_logs')
    op.drop_index('idx_http_logs_user', table_name='http_request_logs')
    op.drop_index('idx_http_logs_timestamp', table_name='http_request_logs')
    op.drop_index('idx_http_logs_status', table_name='http_request_logs')
    op.drop_index('idx_http_logs_path', table_name='http_request_logs')
    op.drop_index('idx_http_logs_method_path', table_name='http_request_logs')
    op.drop_index('idx_http_logs_errors', table_name='http_request_logs', postgresql_where='status_code >= 400')
    op.drop_table('http_request_logs')
    # ### end Alembic commands ###
